(define (reverse ilist)
 (define (iter-reverse li tmpli)
  (if (null? (cdr li))
  (append (list (car li)) tmpli )
  (iter-reverse (cdr li) (append (list (car li)) tmpli )))
 ) 
 (iter-reverse ilist (list ))
)

(define (deep-reverse ilist)
  (define (deep-iter-reverse li tmpli)
    (if (null? (cdr li))
     (list tmpli (reverse (car li)))
     (deep-iter-reverse (cdr li)(append tmpli (reverse (car li))))
      ) 
    )
    (deep-iter-reverse (reverse ilist)(list ))
  )
